site:
  title: Корпоративная документация
  url: https://docs.company.com
  start_page: auth::index.adoc

content:
  sources:
    - url: ./docs-module-a
      branches: HEAD
      start_path: .
    - url: ./docs-module-b
      branches: HEAD
      start_path: .

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/site

runtime:
  fetch: true